// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const faviconPng = 'assets/images/favicon.png';
  static const kopegtelLogoFixedPng = 'assets/images/KopegtelLogoFixed.png';
}

class AssetsSvgs {

}

